{"name": "test_1_cases_create_purpose", "status": "broken", "statusDetails": {"message": "NameError: name 'time' is not defined. Did you forget to import 'time'", "trace": "@pytest.mark.regress_tap\n    def test_1_cases_create_purpose():\n    \n        #Перехожу по ссылке в ТАП\n        browser.get(url_TAP)\n        browser.implicitly_wait(20)\n        f = ContractsPage(browser)\n>       time.sleep(4)\nE       NameError: name 'time' is not defined. Did you forget to import 'time'\n\nautotest\\tests\\test_TAP.py:16: NameError"}, "start": 1714130329786, "stop": 1714130332112, "uuid": "0aa1023d-53f7-4526-b551-738e5553c9d8", "historyId": "d7dd4efe7d23114c7ead42e4ae643bd3", "testCaseId": "d7dd4efe7d23114c7ead42e4ae643bd3", "fullName": "autotest.tests.test_TAP#test_1_cases_create_purpose", "labels": [{"name": "tag", "value": "regress_tap"}, {"name": "parentSuite", "value": "autotest.tests"}, {"name": "suite", "value": "test_TAP"}, {"name": "host", "value": "Arutyun"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "autotest.tests.test_TAP"}]}